version: '3.8'

services:
  nginx:
    container_name: infra_nginx_1
    image: nginx:1.23.4-alpine
    restart: unless-stopped
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./nginx/certs:/etc/nginx/certs
      - /var/log/nginx:/var/log/nginx
    networks:
      - backend
      - frontend
    ports:
      - "80:80"
      - "443:443"
    command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"

networks:
  backend:
    external: true
  frontend:
    external: true
 
